FROM amazon/opendistro-for-elasticsearch:0.7.0
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ingest-geoip
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ingest-user-agent

